#!/bin/bash




function post_compile {

  cp ./lib/saito/boot.js ./web/saito/saito2.js
  cat ./web/saito/saito.js >> ./web/saito/saito2.js
  mv -f ./web/saito/saito2.js ./web/saito/saito.js

}

function reset_bundler {

  rm -rf ./bundler
  if [ ! -d "./bundler" ]; then
    mkdir -p bundler/default/mods
    cp -rf ./lib bundler/default/lib
    cp -rf ./config bundler/default/config
    cp -rf ./mods/* bundler/default/mods/
    for md in bundler/default/mods/* ; do
      rm -rf "$md/web"
      rm -rf "$md/sql"
      rm -rf "$md/www"
      rm -rf "$md/DESCRIPTION.txt"
      rm -rf "$md/BUGS.txt"
      rm -rf "$md/README.txt"
      rm -rf "$md/README.md"
      rm -rf "$md/install.sh"
      rm -rf "$md/license"
    done
  fi

}

function reset_nonpersistent {

  # ensure deleted
  rm -f ./web/saito/saito.js

  # we explicitly don't delete registry/balance databases
  rm -f ./data/appstore.sq3
  #rm -f ./data/covid19.sq3
  rm -f ./data/hospital.sq3
  rm -f ./data/records.sq3
  rm -f ./data/archive.sq3
  rm -f ./data/explorer.sq3
  rm -f ./data/timeclock.sq3
  rm -f ./data/arcade.sq3
  rm -f ./data/chat.sq3
  rm -f ./data/database.sq3
  rm -f ./data/bank.sq3
  rm -f ./data/escrow.sq3
  rm -f ./data/log.txt
  rm -f ./data/*.sq3-journal
  find ./data/blocks/ -name '*.blk' | xargs rm -r
  rm -f ./data/shashmaps/*.smap
  rm -f ./data/blocks/*.zip
  rm -f ./data/blocks/*.segadd
  rm -f ./data/tmp/*.blk
  rm -f ./data/tmp/*.zip
  rm -f ./config/options

  rm -rf ./mods/appstore/mods
  mkdir ./mods/appstore/mods
  rm -f ./mods/appstore/bundler/dist/*

  rm -f ./mods/forum/web/img/thumbnails/*.png
  rm -f ./mods/registry/web/addresses.txt
  rm -f ./mods/appstore/mods/*
  rm -rf ./mods/appstore/bundler/mods/*
  rm -f ./mods/appstore/bundler/dist/*
  rm -f ./mods/appstore/bundler/*.js
  rm -f ./mods/appstore/bundler/*.json
  rm -f ./logs/*

  #let the system know that users pre-existed a reset.
  echo "update users set latest_tx = -1;" | sqlite3 ./data/rewards.sq3
  
  if [ ! -f ./config/modules.config.js ]; then
    cp ./config/modules.default.js ./config/modules.config.js
  fi
  if [ -f config/options.conf ]; then
    cp config/options.conf config/options
  fi

}

function reset_persistent {

  rm -f ./data/forum.sq3
  rm -f ./data/registry.sq3
  rm -f ./data/rewards.sq3
  rm -f ./data/forum.sq3
  rm -f ./data/tutorial.sq3

}







if [ "$1" == "nuke" ]; then

  echo ""
  echo ""
  echo "     _.-^^---....,,--        "
  echo " _--                  --_    "
  echo " <                        >) "
  echo " |                         | "
  echo "  \._                   _./  "
  echo "     '''--. . , ; .--'''     "
  echo "          | |   |            "
  echo "       .-=||  | |=-.         "
  echo "        -=#$%&%$#=-'         "
  echo "          | ;  :|            "
  echo "      .,-#%&$@%#&#~,         "
  echo "  -------------------------  "
  echo "  NUKING YOUR SAITO INSTALL  "
  echo "  -------------------------  "
  echo "  (resetting configuration)  "
  echo ""
  echo ""

  reset_nonpersistent
  reset_persistent
  reset_bundler

  if [ "$2" == "dev" ]; then 
    node webpack/webpack.dev.js
  else
    node webpack/webpack.prod.js
  fi

  post_compile

fi

if [ "$1" == "reset" ]; then

  echo ""
  echo ""
  echo "  --------------------------  "
  echo "  RESETTING ALL BUT CORE DATA "
  echo "  --------------------------  "
  echo "   (resetting blockchain)  "
  echo ""
  echo ""

  reset_nonpersistent
  reset_bundler

  if [ "$2" == "dev" ]; then 
    node webpack/webpack.dev.js
  else
    node webpack/webpack.prod.js
  fi

  post_compile

fi

if [ "$1" == "recompile" ]; then

  echo ""
  echo "  -------------------------  "
  echo "   RE-COMPILING JAVASCRIPT   "
  echo "  -------------------------  "
  echo "  (resetting configuration)  "
  echo ""
  echo ""

  reset_bundler

  if [ "$2" == "dev" ]; then 
    node webpack/webpack.dev.js
  else
    node webpack/webpack.prod.js
  fi

  post_compile

fi



