// Generated by dts-bundle v0.7.3-fork.1
// Dependencies for this module:
//   main.d.ts

declare module '@fullcalendar/google-calendar' {
    module '@fullcalendar/core' {
        interface OptionsInput {
            googleCalendarApiKey?: string;
    ***REMOVED***
***REMOVED***
    module '@fullcalendar/core/structs/event-source' {
        interface ExtendedEventSourceInput {
            googleCalendarApiKey?: string;
            googleCalendarId?: string;
    ***REMOVED***
***REMOVED***
    const _default: import("@fullcalendar/core").PluginDef;
    export default _default;
***REMOVED***

