module.exports = {
  core: [
    'alaunius/alaunius.js',
    'appstore/appstore.js',
    'archive/archive.js',
    'chat/chat.js',
    'chess/chess.js',
    'email/email.js',
    'encrypt/encrypt.js',
    'explorer/explorer.js',
    'escrow/escrow.js',
//    'faucet/faucet.js',
    'hospital/hospital.js',
    'imperium/imperium.js',
    'pandemic/pandemic.js',
    'poker/poker.js',
    'qrscanner/qrscanner.js',
    'relay/relay.js',
    'registry/registry.js',
//    'settings/settings.js',
    'solitrio/solitrio.js',
    'testing/testing.js',
    'twilight/twilight.js',
    'wallet/wallet.js',
    'wordblocks/wordblocks.js',
    'design/design.js',
    'arcade/arcade.js',
    'website/website.js',
  ],
  lite: [
    'alaunius/alaunius.js',
    'alaunius-settings/settings.js',
    'alaunius-labs/labs.js',
    'archive/archive.js',
    'appstore/appstore.js',
    'chess/chess.js',
    'chat/chat.js',
    'debug/debug.js',
    'email/email.js',
    'escrow/escrow.js',
    'encrypt/encrypt.js',
    'hospital/hospital.js',
    'imperium/imperium.js',
    'gettokens/gettokens.js',
    'qrscanner/qrscanner.js',
    'pandemic/pandemic.js',
    'poker/poker.js',
    'relay/relay.js',
    'registry/registry.js',
//    'settings/settings.js',
    'solitrio/solitrio.js',
    'testing/testing.js',
    'twilight/twilight.js',
    'wallet/wallet.js',
    'wordblocks/wordblocks.js',
    'design/design.js',
    'arcade/arcade.js',
    'website/website.js',
    ]
}
