***REMOVED***
  core: [
    'appstore/appstore.js',
    'archive/archive.js',
    'chat/chat.js',
    'email/email.js',
    'encrypt/encrypt.js',
    'explorer/explorer.js',
    'faucet/faucet.js',
    'hospital/hospital.js',
    'poker/poker.js',
    'qrscanner/qrscanner.js',
    'registry/registry.js',
    'settings/settings.js',
    // 'twilight/twilight.js',
    'wallet/wallet.js',
    'wordblocks/wordblocks.js',
    'design/design.js',
    'arcade/arcade.js',
  ],
  lite: [
    'appstore/appstore.js',
    'chat/chat.js',
    'debug/debug.js',
    'email/email.js',
    'encrypt/encrypt.js',
    'hospital/hospital.js',
    'gettokens/gettokens.js',
    'qrscanner/qrscanner.js',
    'poker/poker.js',
    'registry/registry.js',
    'settings/settings.js',
    // 'twilight/twilight.js',
    'wallet/wallet.js',
    'wordblocks/wordblocks.js',
    'design/design.js',
    'arcade/arcade.js',
  ]
***REMOVED***
