module.exports = [
    {
        id: "identifier",
        icon: "<i class='fas fa-user-tag'></i>",
        reward: 50,
        title: "Register Identifier",
        event: "register identifier",
        description: "Not a robot? You are eligible for tokens from the Saito faucet. Register an identifier to get started.",
        completed: false,
        action: function(app){app.modules.returnModule('Tutorial').registerIdentifierModal();},
    },
    {
        id: "backup",
        icon: "<i class='fas fa-download'></i>",
        reward: 50,
        title: "Backup Wallet",
        event: "user wallet backup",
        description:"Backup your wallet and we'll send you a heap of Saito tokens, enough to use the network for a long, long, time. Backing up your wallet is important as it provides you with the ability to restore your account.",
        completed: false,
        action: function(app){app.modules.returnModule('Tutorial').welcomeBackupModal();},
    },
    {
        id: "addcontact",
        icon: "<i class='fas fa-qrcode'></i>",
        reward: 50,
        title: "Refer Friend",
        event: "user add contact",
        description:"Sharing is great. Don't keep Saito to your self - tell your friends.",
        completed: false,
        action: function(app){app.modules.returnModule("Tutorial").inviteFriendsModal();},
    },
    {
        id: "screen-survey",
        icon: "<i class='fas fa-ruler-combined'></i>",
        reward: 50,
        title: "Hardware Survey",
        event: "screen survey",
        description:"Let us know a bit about how you are using Saito. Use an anonymous acount if you like - we are not tracking you.",
        completed: false,
        action: function(app){app.modules.returnModule("Tutorial").screenSurveyModal();},
    },
    {
        id: "survey",
        icon: "<i class='far fa-clipboard'></i>",
        reward: 50,
        title: "Take Survey",
        event: "user survey",
        description:"Let us know what you think. Use an anonymous acount if you like - we are not tracking you.",
        completed: false,
        action: function(app){app.modules.returnModule("Tutorial").surveyModal();},
    },
    {
        id: "newsletter",
        icon: "<i class='fas fa-envelope'></i>",
        reward: 50,
        title: "Sign Up for the Newsletter",
        event: "user newsletter",
        description:"Stay up to date with the latest Saito news.",
        completed: false,
        action: function(app){app.modules.returnModule("Tutorial").newsletterModal();},
    },
    {
        id: "suggest",
        icon: "<i class='fas fa-vote-yea'></i>",
        reward: 25,
        title: "Make a Suggestion",
        event: "user suggest",
        description:"Let us know your feedback, get involved with the project!",
        completed: false,
        action: function(app){app.modules.returnModule("Tutorial").suggestModal();},
    },
];

