const path = require('path');
const saito = require('../../lib/saito/saito');
const ModTemplate = require('../../lib/templates/modtemplate');
const ModalRegisterEmail = require('../../lib/saito/ui/modal-register-email/modal-register-email');
const SaitoHeader = require('../../lib/saito/ui/saito-header/saito-header');
const SaitoOverlay = require('../../lib/saito/ui/saito-overlay/saito-overlay');
const Data = require('./lib/data');


class Website extends ModTemplate {

  constructor(app) {
    super(app);

    this.app = app;
    this.name = "Website";

    this.description = "Module that creates a root website on a Saito node.";
    this.categories = "Utilities Communications";
    this.header = null;
    this.overlay = new SaitoOverlay(app, this);
    return this;
  }

  initializeHTML(app) {
    if (this.header == null) {
      this.header = new SaitoHeader(app, this);
    }

    this.header.render(app, this);
    this.header.attachEvents(app, this);

    if (document.querySelector('.header-icon-links')) {
      app.browser.prependElementToDom(document.querySelector("#header-icon-links-hidden").innerHTML, document.querySelector('.header-icon-links'));
    }
    if (document.querySelector('.header-dropdown')) {
      app.browser.prependElementToDom(document.querySelector("#header-dropdown-hidden").innerHTML, document.querySelector('.header-dropdown'));
    }

    document.querySelectorAll('#weixin-link').forEach((element) => {
      element.onclick = (event) => {
        // This QR comes from msng.link at this location:
        // https://msng.link/o/?https%3A%2F%2Fweixin.qq.com%2Fg%2FAQYAAP6SZ8iLZ2exjHm6K1gcYvsqSuHGGzD6yDgHy_Axy6fXAJHA6NV7117FliL-=wc
        // The QR codes generated by wechat directly expire after 7 days and only allow 100 or 200 people to use them.
        // msng.link claims to solve this problem.
        // I don't want to put an iframe if not necessary so I copied the QR code from msng.link instead...
        // If this stops working, we'll have to make another plan.
        // 
        // This seems to last quite long. The regenerate this, get the QR code from Wechat and copy to your PC. Go to msng.link and follow the links. View the source code and copy the img out.
        this.overlay.showOverlay(app, this, `<div id='weixinqr-overlay'><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOQAAADkCAYAAACIV4iNAAAbFElEQVR4Xu2d0XLjuA5EZ///o+eWs3urEomZc9gBHWe353FEAWCjGwBlW/nr169fv399w7/fvz+6/euvvz5Ecb1+KsQJv1cbJlazvxOxGb/X+E0cZg3h8qo2KO7J6w8VVJDvEJ0grEmQ8fOqBF3F/pNipfwkBZZs2usV5EBnThJYQd4p+qqitmKaWFdBVpDIIyMUs4YcvaoNinvy+k2QpnLvBrDqIHSG3PWxWm9Gq+t95p4kdsI16bJmzxMkn8hFsj/CbBWX8UN2DV9PYVJBXpCtICeoxuOo8ULCqSANios1puKYyrbr3oirHXIX1Wx9kt8K8vHI9fJxRAb/x7sqSMY1IWxH1qwTE8cNX0/pAkfWhCjmjEWgmA1PxHb1Y2wmsdNZLiHB1D00JVDsaa4SHClfE9wzuBqe7OL6WF9BXlAzQCdEIlIbEhAZH9cptmR/FHsFaRC452aViwqygryxiboMid4+bEnsUFGi2NOiZeySLI2NCrKCrCAFB4yY/lWCNGORGbcmQJmwMZFAimPqoQ7havZCaya6oe2879eZJ+0U+6qrEmZJbl7qDFlBJvK730PkMgRNHkYkfid2TMIw+6XYK8hPHk4Q+CbBBnyyY2yYNeQnuU5+DUEryI+/PKogK8hEi2/3VJAfoTMFiDAzuJqEGT8v81CnI6tJKa+hpBuCtkO2Q/4y4yg9GEhETTZZAjMrzP5nPM2cOykWsx8qHuTDXE/yaz4TNvtLCtvLdkjzlOq6poI0FK0gCaUK8vGVocvvEitIos3cdepUU10m6Rhf3eVU7ISRidPYaIc88GV6kxzq7omN9B4iyhSpK8g/v0fqgQ8KMk3y+/uSEeDUw4dkP0RYY5NsmP2eEgbFT7En08zqnokjh7FB+zV8JRvmevRdVmOY1pgNGiBprE2IQ7E/rk/YJRsV5P3YkmBieEQ5N3wlG+Z6BWlQWqwhMRmzZCMhn/FLRczYoNjbIQ2K9zUVZIZbOyS8Q7eCzIilBJmZ3r+Lqm7SMcy4QmvMuEI23g7n8DY7up7YMON1cd3PzT678zt+1GsgicR0vSRf/4CZcKPr/wVcc4nt3VlBinGs3Zz/zAOJ9qdPHnuyyldXkBVkx2vBgVxie3dWkCIZ7ZDtkHuyylf/9Tv5tDn3p++ceFw/9fTvasfENgErjYEGTGOD1tD1VRzJPWY/lIsJ3JM4pu6pIAMkK0j+g2kVZECsx9P5dsh94CrICnKfNe6OCtLh9GFVBVlBBrRRt2wL0jy+pjn/cZ1m/VOkp1Eq8ZtgYjBSGdxcRLgbc1MYXX3RwzPzTMDERn7NmdjglOynghRPWSmBFeSdngkZn3UP5bOCXCBgKl1S7dshedyk6p/k5pXuqSAXbwMgMSUJJCI9rleQFeRLC/JxnHsf4LOEQsIwY0My4iTJMEKnM2GCK+3PfFHcxJ7EZuzu8Mra2+XNxHHCxkYcMNzbfmPAVOfaBXaquxlQ0gS8v293f4Y4xqbJzy4Gic1dHxZzg8Gf8vC4RgXIxkLrCLdlQW2H/PoIl3RzU03bIe/IVpAXTEj1tgLtAtsOyeffFUZUxU2+TM7Jz1RX2uWNmTwo9vQ64dYOuUB2iijU8ciPIY4hI5FgRa4ktl2Skg9rz2Dwo0fW61fnaMMm4TRqGfBNAilW4+fUfggDup52LoObwWX3PJzkwmBPsRKOCR5TxTEp0rcvBhCwBkQCiUA2ZDQjrPFzaj+EAV03GBjiGAxoDXEizYXBnmIjHCvIQ69NXCXGEIUSakhBSTdjIMWaiCu5h/BIcab9GbtJbJSbCrKCfOPVLlEScSX3JKQ3YjNraIRLYtvF2fgwuE7sVz3UuQZMGzajVQoCxZIk2OzHxEtrqDKbhJo1hAHFsRo3aW/Pup7EnuTX3GNi2c3FSvj4Co9TwVLwZgycsGFG1oSAlEAjNrOGMKA4KkieZtKmQ/mrIMUomYhvongsxxd4t6s5l1WQ9z++SpOXGVkNTyrI4E/atUO6PwVoCDi9JikmZqL7UYJMNpRskO4xyU0qEPlNqqO5h4RvyEfjqcHMdHPC1fih/Zo4piYAws1gP7Efgyt+ufxEIGkydoE1sZsCRAmrIO8ZNdhTcawgh85YhuRJMirIjwgkpDfF0FRy6pJJbFT4Vg+gzD27vDGFgPb/uE46UB97kJGJQAwpjB8ijiGF2S8lvR2yHdJwmvj6VnCe8V1WU3GI9FPV0Qid1hihk41T102BId9kw+SKupIh8ARvTK4m9mNsVJDEvPC6SXJo+su3kZiMA7JhyFdB8tSwHFnbIQ1Fz5zd9j3zHSQmtpCdfciuKWJG6KbLvI9lyi8VmKnYO7ISkxbXTZIDsyO3VJD7xdOIqYIUQkiAnGB9Bbn/2hODmclnO6R4kTABaZ5CUgV6XN/1Q+utOIkEhmzky8RKcZCPx3WTi8QPYbA8Lw18NZD2nPhNMKI47PWRkZXIZDZYQXLXSYSS4Jr4qSCt5P68roIUOBJBiYzCBXb/VXejQrjya4oj7dfafb8u6VSJn+s9id8EI5Njs6aCFCgRQStI/oJ6Ioz/pCDpvayGbPRkL0mG8UvV0NiY6jIUC42OU3FQLkT9iZaQ34QDUSDiJiqwwgT+SQpTTJaYVJB8diMxrcAngZ0gxSMOEoYhW7KG/FaQ8r26FWQFmQiQJgJTcMyaidiooFLxTLtd4nfk51cnqqMZN3dJkXQyk4zE7gQZv/Phwy727ZCyQ+5+dc5ULCMmEvEEyRMbiQC/q8KaXJjYqDiYfJpYdkU8lb8kNrqHMKP7H9dXuG4/ZU0dPSMZhjiGoDRq0F4SjExcZn9JbESuxK/B4ERRNn4n1hBmxkcFKb7t0w75vAdDFeT9BVztkKKUUYcw3Y26rrFBcaQjHlX7xK+ANXoibHAyvr+6hjAz9tsh2yGXPCFyVZB32AizMUFSJTdV2ASbJPlEdUziMGDvrpnaG2Fvnszuxp6M+Y97aGQ1mNB+TWyJH3NWT7h1G1kryAk67tswpDBWiaAVpPv4YVcH5mMdlb/rxx67gaSVLqkeU6R9v8ckDgPs7pqpvVWQ/EUPwsh01XbI8PxHwqgg+XemhGFC4LSQU8Mwhe1fJcip1kznB3NWpeQkRDIJTey+cqxUlBJMyOZKkAbXXTGZOEy3o/wZjEws22fICtLQhteY5JAVQwKy8bhOsSR+yGYFuc5MBXnBJSGfIT1V2MTGVKwknsQP2awgK0jF+YR8yvBlkSEs2Z2KlWJJ/JDNCvITQdLPr5LKbhJoEkaEnLhuzrJmzVdjMUeBCVwTG2b/tMbs77vOcgYTyq/5OMlwHn9+VUHyB9iULHPdENYQh5Ke2CCxrbqdefjyjFhX2JvYTM7er6kgdxH7ZP0E2SZCqSDvKE4UjwpSfl5I1XGC5MZGBXlHiTpI0g1MwenI+utXR9bgRdAniokhbNIxTpC8guQiZsb4ZfeeeGPACYKa7kZkM3GZDkmxGDFRrORj6noiJuPbFAuyQ535cT/lNMlnEjvFsRIk7f9tfxXkx+8+GqCNuMhOQgKTUFpTQWZn1etdlN8KUvycZ0XWpKJWkDOkJpJPTB7HhHP5uySGW1Qs2yFDEVeQFeQxoV+/GGDIRkpPzgJmhCMQTLejNUkcz7rH5GYXI8plep3iWI10hje78ZgR3dg8EdvK7+0pq0k6bcAEb9bQSEOxmmRMxFFB3hlRQZJK1tcryIG/UVhBVpCZ/Ba4dWT9+Cq+Z4kr8UMTwdtDAXjYYPxOkIvi6MgqOySdsZKnSSY5hgQUG11fkWB3LDY2jDAScU3sb3lugSlhIn8TT0ynYjc4Gj6+XzO1P/ymjkkGVV1jwwBAQNJ1IyYTK+23grxnc4qwVEATDpicEz+n9ldBXpA2yakgiZ4VpCnKSxHT7yEnCGpsmBRT9aPr7ZCfnFs6shr6/XHNWIfcfQ3kmOOABCQ4um4eJJgzsikwpou+92VsJqwxmJjzLPlOPj6i8ZN8mgJrzp3GT4IR5XSppQry/gdPCHwCOiGKsTlBHONnt5isxrMJG2a/z/JDnEiEX0GGX5V7RpcxQjEEJeIYPxMkn7Bh9vssP4RrBbn4zM0Ix6wh8E+Q2tg0BP2O2Nsh3dmccvOGY0fWjqyGKFQMeoa8I0RFNhpZJw7elMzV9VOjSNIhKf4k1u/C1WCdEGliP8/KDe2P8m2vJ/vBDjkBtN3A+3UJyQ3QCUgUfxLrd+FaQfLXCynf9nrCtQpS/NCUElBB7o9rE4WB8vK4nnxMZ+yaNRWkEFcCEoFfQVaQUwVm++dXyVhIhH57uiR+BmXWkC8TP9lIrpNoTVxkYxVXghndY2K9xmI6lSmWuxiYWHdtWr4mx5IKMlFXcA8l/ZWJY4RCkFSQ7uxaQRKThq5XkPe/bJx0YsIx6Uq7Ntsh/0GZEmi0YzqRsbO7hpJu4iIbHVmzs+x34brM14n3spoRx6wh0n8XkK/idyViwtXEToUvKR5JrOZBSdIR6Xx7KlaD25EXJRMpHoCYNRXkn18vkhCngryzynDRrEmEfiso7ZD3sw1VXUPqCRtJpyLimNgTvwkZKdZ2SPnxwy7ZkkpO3XHVZc09RLapc9guRonfBNcKsh1y+Sa0pDpSFa4g+ShQQf4wQSaVPek65MeMKxN+TRwTxcMUC1pjxGT2Q4VtAtfExol7zIOU78J1ORWd+PnVd20w8WsIXEHyOZtwNLmpIA/9HtKATwlsh+TRijrq43rSIRJhUD4NJxK/dE+y/2fh2g4pkE4elAizI0sMqUkYzyp0JJTkIVZyz48X5ASQE+xbkY9io+u2Y9AZy5CexHMq1hPYG1InfpOjQHJPEtvuPZRvU0ze+Hnic8jdzZiqvRITJceI2sRKYJuuSiKeitXsh9YQrnS/vZ74Se6x8XxlHXGkghz8cSqBXUFmVE7EldyTRbd3F3Gkgqwg9xj1bvWzSJ/4Se6Jgdi4cUyQu3+OznQDcz5KRji6x+BHCTXAJmcqY5fiN7jSGhM7YWSOGBTH6ghC+zd+jQ0TG3HNYERrlseUCvLrfx/SkKCC5N9DGhyvaxJcK8jf/MHyBEgmoUnVomqZ+DX3kF/zIIj2a7rORFc1sSaYVJCLF0lR0g1oFSTT0WBEaybElYi4gpTvjerI2pGVxsAJEVeQhwTJdfy+InkQlPgxnZjsmlhplHxcPxHLhE3av3nYYuKgTj0Rh7GRdHNjN8HA2N1+yZUxmhDWVGHybUAiGxUkf//V4FxBMo4rLlaQF1QqSCZSBekmoKTJVJAV5K1QE5EqyIOC3P0uKyXLzOzLVh28uZweRtB4ml434xjhZEidxvf+Popjdd41+6PYTtggnyevU76mJqvtL5ebBCdCMQkk3wTaVMJ+cqymYJr9EZYnbJDPk9eJWxXkAn0CbSphhmyvWjwqyIwFxK0KsoJUzKLC0JFVwYgfY40J8vrFAPrWTVJhzZapAj1smM701fOTOd9OjOQTmEyRgLA3uNMaE6spHoQb7YXu/+x6sj/ypb5cXkHeYSSiGBKQDVPormsMyU/cY751Y3hk1hCpk+K4a9M0g6n83j72SEBK7kmApCplyDfh94SNCpI//zRCMsXR2CEuneJ8BRn8EqWC5J9SGcKaNbvi+fGCPPFeVkPY3W43NTYkCaNxZGqEI/KdIPBUZ6bYEz/GZsKj3e53insrXt0+h5wItoLkB1AkckPgxIYhORWtKb/kx8RaQS5GPEpQ0kFWySDwKY6HzYQEZDfZH9msII0cufAZK8SrdshPUCTgDMkrSKYoYWRwZi9ZcUwmOIqFeFVBVpBLBHqGvMNixPSvFiRtbjUWms/LkqpLBDWjpNkPnYnN/qiyJ3GYsdb43cXR5IpsWp4QLtTNzdGH8ksxfHadcFryc/cpqwnuu5JhqiWBdGp/RhjGN60hgpriQTgaDL+LA4TPavysIBcPV0ySCTgikkmGSWhCtgry47uL2iHXZ+jtjz1OEbaCNMjymnZIxoi4Rhiyh79XJH62BTkVrN3U+3WmA5JdspGMdBNnOXPeNZ2Z9m9incAoiYMInNic2G8srsUrU9/HM3KGrCC58q3GMRpZK0iH64QoqbCZXNDxKRbx7kOdCtIRh3CiLrRKKBEpJSvZpeumAJnY2iGH/qS5AXtijSEx+SEbHVn52y8GI8rD6noFKf5gawKsqaiJXRoTTiX0WfshTEwctMaMYxM2aC/J2c7ck/il48SUX8NPfMlVskFKaGLTgGI2nPh+1n4oNhMHrakgCeWZI0k6AVSQnJ/bF9JPCZ9CIbGtznI0oidnVSNq2stUgaWzehKHyW/i19itIEXGjBCEmS8vMXHQGiOmCRvJZsmvEXHityPrBGpD3/YxoSREMXZ315g4aE0FyaibTvZtHdI4NmMRw8ArTvgxNs0ajv7jCpP0q00SW9pBKBbj1/CEOlFiYxd3c7Y7FYfhEY6sJjjj6FWBM7GbNbv7IxEYcRkbSf6SQmD8VJD8t0gryOBviiTkIzIaQZtORWIyHYJsTH0OeaLQGRwpFxP5NTgvjw+7f2wndZQA9QzgDCnMmt39me6WCIPuMfkjGxXkbrb/Xm94tP3lcjNKkZAe16kKmaQTqSceYBjoJ/wQHiaORGyrXEzgSqK2BDVcer/G4Ej7S7GmPRu/FeTlpV0GNALekM1UywlimP3sjsKmAE1glBSYCnKo25lKeII4uzbthECCo+sTYlwVBhM/ibiCdNlJuNUO2Q65/U2kCvKgIHf/+pUZCUy4SYfYvcecQyc6c0JQM9IZHCl+k69dXM0omXSHZL8JjskEMBGbsbH9tz1MgpVj8XHDV8lWQfLDM3PencgnicD4MGsMPykWY8PEkqypIC+oGRGbjkJJTyq7SbCJ7auFrh3SZCJbU0FWkOrzMaIXFYLdAkX+PrtuuhvFYmyk8dF9FWQFWUFeOPDSgqTxZqV4c6A3a7461lElNLGvzlhU5Yxd6ijp2c7YpfincHvvxxwFKK7keuLX3GMwSoSNHbKCdL8gJ7JQATJPak2CK8iPmTDiMhyn/JkiTBx5K8L0sYcJljqZAeVExTE2KfZ2SEMjfpprOOA87a1K/Jp7DLdMAb3pq4L8CInpVHuU+Hs1VVjj1yS4HfKHd0j6tYchnyEK2TFEMlXpvR8Tl7GZiIn2e+o67ccIn2JLbCS5mPBDeNBe/3+d4p/qqvh7SBMwBWtsVJAGJV5DBExIPjHWG45McICKJyO4XkHxV5ACWQLRng8pycaPCHdkSQX5+wOOhIcFnXJcQQokCcQK8m8Qd0mbdNkkFxN+dvf2Ga0o/jFBXh/q0HgytUHyswKGfBNoQsNqCcVhjJhYaYRL4jAkp4lgtb/vusdgvbsmEdcUrrePPUgoCQkMIAlBKVbjN1kzgUGy34T0BqMJ4SexTdyT5I/uqSDFj5zNaGVITskw1yvIO0oT4jK4PiPHFWQFuawDE52rHdKU2I9rvlWQu59DnqpQRL6pM6WpwobEu2me8GtsTOTH+CGMjI2kq+7ibtYbzMx+CBMTy/bnkCZ44/i6poI8MwZO5MLYSMSV3GNi2V1jOF1BXt510w7pPp4w5CLCTpDP2Kgg75lohyR2yvMtmTEEpZHH2KggKRM8iSTFf3VPkosKUuQvAZZGcuEWv5A+RYJXidUUHIPb7hqT3yQ2Y/eG/fWhDm3GPIEyCaZgDQCJDRqTpj7g3fVj9ku5MdfN/pJOPZGLhDeEW7Jfg6NZQxxYduIKUvxFInhDnilS9NCKiGUIYNYkBDXEqiB5FDY5xhclJ1Xr1D1UuRO/JJSHTVpTQZ75gXKCq+GIEYYpbrTGFLKOrPCmctNBDNC0hq5TstPrZn9EaiOUpDgm95C4kv2m2Ca4fVmQU8ES+DQCpXFQt0vt0n1EHLr/cT3BxOx3N7aJOFb7TYoUxWL2RjaWZ73gRd/E+bdpbPcMaYiTrDHESewSCEkykjgMMchuEqvBdTe2iTgqyPXnyhWk+AICCcVc3yW9IWzid2KEqyD5uUKSm3bIcAw0YFNnTmxMCKGCvCN/ClfK8apI4+8hyWh6fQKEq29jk0a4iU72rO5mHq4k+zE47hYcUwiSMyRxwOzf+DVrdrWwxITeGLDrxK5/VtKJOCeAriBdFzpRHJN8mnvMGsv9/6+rIMPPFHeBriArSMOZCrKCNDwZ+XiFRsm3BxjBN6BoA0knM/eYNRSbwqQj65nXBhrwKYEJYSeI86zjRLI/wizZv7nHrKHYDCe2/7bHrtNVJXz8X5J0Og+qDV+qstkPxZo8XEkSTHGs9kKkN53K4E6xTWBkYjUPcQxPiBcncH3b3+7f9qBADSkqSP5bH886hxqSV5D3bFSQC4ZSNTSP2k2BeUb1p72kRewEcUy3S0Q8EavBsR1yMSYSyY1QCPwKkh+ctENmx6eJ4rGcJmlkJdKb0SqpqIkgJ85lU7FSwuj6Z2dvg8tX1yQ4Jj6TorzLx6miTPszfsx+8Qy5C8BqtJoiOY1BCZHMPQbIr8ZmEkqkmLpuMJnwNYErxfEsXI0fs98KEn4feers1g45MypWkISA+GvBKcm/2oWeOV6T4Oh6R9Y10XYnNtO5BKVxifHzozpkQtBktKJ7DLCYHVGUVHLgM1MTK+03KVImdoMR5dyIj2L5ruNSsv+3IvwqD3UoOeZpYJLAxK8Bm4RARDIdsoLksbeCFN3BPPh5JbIZoV9FWkFy2aJiaHCnwlZBVpBvTKwgK0hCYFUsOrKKlxWZSt0OSfS7X2+H/PhO4Jc6Q9ITVPNk1ggnGXH2qcYdkgSc+DTnbGOXhGJsTORz5YdyTPlNYjfn+eTh2HJ/r/JQZyKBlKwpUZuk0shaQfIDmQpSnH2myEiVLDmMV5Duu6uUw3ZIHq8JQ/McoR1S/A7TiPpEMqhAGZ8dWbOua7BNeLE7JakzpAmW1pzqdsnYl1T/JBmEycR189FQ4ich0qvkYqqw0REq8WO4h09Zk4TSZk6d5QxIBhQT/wQuX7VRQd4RNBxIcE94Qzxa5o8e6iTBUyAV5ASq6/Fsopu3Q/IZMhG+EXU7pPhTAhMkn5HgRyvtkP+BDnmCOCubVGEmzp2GsKYbUKwGM6qOyX4Tv0kujB9aY/ZnCh/li65TnGZ6e6yhfK78mHte9k8JmATSaFxBrv/CUvIAxhD5T2tMPivIxa89vgq8vZ+6jklgBcloJyRnq/srTD6TWKnrGJtJgSK/7ZByjCAgDXH26cgjzrP8dmTl7FGz6Mj6D4YEFInNAPksYZizDu2XqdWR9ad1yP8B8qxUAMO4dnUAAAAASUVORK5CYII=" style="display: block;">
        </div>`, () => {})
      }
    });

    document.querySelectorAll('#whitepaperLink').forEach((element) => {
      element.onclick = (event) => {
        app.browser.logMatomoEvent("Navigation", "HomepageNavigationClick", "HomepageWhitepaperLink");
      }
    });
    document.querySelectorAll('#litepaperLink').forEach((element) => {
      element.onclick = (event) => {
        app.browser.logMatomoEvent("Navigation", "HomepageNavigationClick", "HomepageLitepaperLink");
      }
    });
    document.querySelectorAll('#arcadeLink').forEach((element) => {
      element.onclick = (event) => {
        app.browser.logMatomoEvent("Navigation", "HomepageNavigationClick", "HomepageArcadeLink");
      }
    });
    document.querySelectorAll('#developersLink').forEach((element) => {
      element.onclick = (event) => {
        app.browser.logMatomoEvent("Navigation", "HomepageNavigationClick", "HomepageDevelopersLink");
      }
    });
    document.querySelectorAll('.left.desktop .logo').forEach((element) => {
      element.onclick = (event) => {
        app.browser.logMatomoEvent("Navigation", "HomepageNavigationClick", "HeaderLogoHomepageLink");
      }
    });
    
    document.querySelectorAll('.website-newsletter-subscribe').forEach((element) => {
      element.onclick = (e) => {
        this.mre = new ModalRegisterEmail(app);
        this.mre.render(this.app, this, ModalRegisterEmail.MODES.NEWSLETTER);
        this.mre.attachEvents(this.app, this);
      }
    });
    this.initializePrivateSaleOverlay();
  }
  
  doPrivateSaleOverlay() {
    let doPrivsaleSignup = this.app.browser.parseHash(window.location.hash).private_sale;
    if(doPrivsaleSignup) {
      this.mre = new ModalRegisterEmail(this.app);
      this.mre.render(this.app, this, ModalRegisterEmail.MODES.PRIVATESALE);
      this.mre.attachEvents(this.app, this);
      window.location.hash = this.app.browser.removeFromHash(window.location.hash, "private_sale");
    }
  }
  initializePrivateSaleOverlay() {
    window.addEventListener("hashchange", () => {
      this.doPrivateSaleOverlay();
    });
    let oldHash = window.location.hash;
    window.location.hash = `#`;
    window.location.hash = oldHash;
  }
  triggerPrivateSaleOverlay() {
    window.location.hash = this.app.browser.modifyHash(window.location.hash, {private_sale: "1"});
  }
  respondTo(type) {
    if (type == "private_sale_overlay") {
      let obj = {};
      obj.initializePrivateSaleOverlay = this.initializePrivateSaleOverlay.bind(this);
      obj.triggerPrivateSaleOverlay = this.triggerPrivateSaleOverlay.bind(this);
      return obj;
    }
  }
  webServer(app, expressapp, express) {
    expressapp.use("/", express.static(`${__dirname}/../../mods/website/web`));
    // TODO: change every reference in the site from /website/* to /* and remove this line
    expressapp.use("/website/", express.static(`${__dirname}/../../mods/website/web`));
    expressapp.get('/l/:campaign/:channel/:subchannel', async (req, res) => {
      res.sendFile(path.join(__dirname + '/web/marketing/marketing.html'));
    });
    expressapp.get('/l/matomohelpers.js', async (req, res) => {
      res.sendFile(path.join(__dirname + "../../../mods/matomo/matomoHelpers.js"));
    });
    expressapp.get('/l/maketrackinglink', async (req, res) => {
      res.sendFile(path.join(__dirname + '/web/marketing/linkmakerform.html'));
    });
  }
}
module.exports = Website;
