// Generated by dts-bundle v0.7.3-fork.1
// Dependencies for this module:
//   ../../../../../@fullcalendar/core
//   ../../../../../@fullcalendar/daygrid

declare module '@fullcalendar/timegrid' {
    import AbstractTimeGridView from '@fullcalendar/timegrid/AbstractTimeGridView';
    import TimeGridView, { buildDayTable ***REMOVED*** from '@fullcalendar/timegrid/TimeGridView';
    import { TimeGridSeg ***REMOVED*** from '@fullcalendar/timegrid/TimeGrid';
    import { TimeGridSlicer, buildDayRanges ***REMOVED*** from '@fullcalendar/timegrid/SimpleTimeGrid';
    export { TimeGridView, AbstractTimeGridView, buildDayTable, buildDayRanges, TimeGridSlicer, TimeGridSeg ***REMOVED***;
    export { default as TimeGrid ***REMOVED*** from '@fullcalendar/timegrid/TimeGrid';
    const _default: import("@fullcalendar/core").PluginDef;
    export default _default;
***REMOVED***

declare module '@fullcalendar/timegrid/AbstractTimeGridView' {
    import { ScrollComponent, View, ViewSpec, DateProfileGenerator, ComponentContext, Duration ***REMOVED*** from '@fullcalendar/core';
    import { DayGrid ***REMOVED*** from '@fullcalendar/daygrid';
    import TimeGrid from '@fullcalendar/timegrid/TimeGrid';
    import AllDaySplitter from '@fullcalendar/timegrid/AllDaySplitter';
    export { TimeGridView as default, TimeGridView ***REMOVED***;
    abstract class TimeGridView extends View {
        timeGrid: TimeGrid;
        dayGrid: DayGrid;
        scroller: ScrollComponent;
        axisWidth: any;
        protected splitter: AllDaySplitter;
        constructor(context: ComponentContext, viewSpec: ViewSpec, dateProfileGenerator: DateProfileGenerator, parentEl: HTMLElement);
        destroy(): void;
        renderSkeletonHtml(): string;
        getNowIndicatorUnit(): string;
        unrenderNowIndicator(): void;
        updateSize(isResize: boolean, viewHeight: number, isAuto: boolean): void;
        updateBaseSize(isResize: any, viewHeight: any, isAuto: any): void;
        computeScrollerHeight(viewHeight: any): number;
        computeDateScroll(duration: Duration): {
            top: any;
    ***REMOVED***;
        queryDateScroll(): {
            top: number;
    ***REMOVED***;
        applyDateScroll(scroll: any): void;
        renderHeadIntroHtml: () => string;
        axisStyleAttr(): string;
        renderTimeGridBgIntroHtml: () => string;
        renderTimeGridIntroHtml: () => string;
        renderDayGridBgIntroHtml: () => string;
        renderDayGridIntroHtml: () => string;
***REMOVED***
***REMOVED***

declare module '@fullcalendar/timegrid/TimeGridView' {
    import { DateProfileGenerator, DateProfile, ComponentContext, ViewSpec, DayHeader, DayTable, ViewProps ***REMOVED*** from '@fullcalendar/core';
    import { SimpleDayGrid ***REMOVED*** from '@fullcalendar/daygrid';
    import SimpleTimeGrid from '@fullcalendar/timegrid/SimpleTimeGrid';
    import AbstractTimeGridView from '@fullcalendar/timegrid/AbstractTimeGridView';
    export { TimeGridView as default, TimeGridView ***REMOVED***;
    class TimeGridView extends AbstractTimeGridView {
        header: DayHeader;
        simpleDayGrid: SimpleDayGrid;
        simpleTimeGrid: SimpleTimeGrid;
        constructor(_context: ComponentContext, viewSpec: ViewSpec, dateProfileGenerator: DateProfileGenerator, parentEl: HTMLElement);
        destroy(): void;
        render(props: ViewProps): void;
        renderNowIndicator(date: any): void;
***REMOVED***
    export function buildDayTable(dateProfile: DateProfile, dateProfileGenerator: DateProfileGenerator): DayTable;
***REMOVED***

declare module '@fullcalendar/timegrid/TimeGrid' {
    import { PositionCache, Duration, DateMarker, DateFormatter, ComponentContext, DateComponent, Seg, EventSegUiInteractionState, DateProfile ***REMOVED*** from '@fullcalendar/core';
    export interface RenderProps {
        renderBgIntroHtml: () => string;
        renderIntroHtml: () => string;
***REMOVED***
    export interface TimeGridSeg extends Seg {
        col: number;
        start: DateMarker;
        end: DateMarker;
***REMOVED***
    export interface TimeGridCell {
        date: DateMarker;
        htmlAttrs?: string;
***REMOVED***
    export interface TimeGridProps {
        dateProfile: DateProfile;
        cells: TimeGridCell[];
        businessHourSegs: TimeGridSeg[];
        bgEventSegs: TimeGridSeg[];
        fgEventSegs: TimeGridSeg[];
        dateSelectionSegs: TimeGridSeg[];
        eventSelection: string;
        eventDrag: EventSegUiInteractionState | null;
        eventResize: EventSegUiInteractionState | null;
***REMOVED***
    export { TimeGrid as default, TimeGrid ***REMOVED***;
    class TimeGrid extends DateComponent<TimeGridProps> {
        renderProps: RenderProps;
        slotDuration: Duration;
        snapDuration: Duration;
        snapsPerSlot: any;
        labelFormat: DateFormatter;
        labelInterval: Duration;
        colCnt: number;
        colEls: HTMLElement[];
        slatContainerEl: HTMLElement;
        slatEls: HTMLElement[];
        nowIndicatorEls: HTMLElement[];
        colPositions: PositionCache;
        slatPositions: PositionCache;
        isSlatSizesDirty: boolean;
        isColSizesDirty: boolean;
        rootBgContainerEl: HTMLElement;
        bottomRuleEl: HTMLElement;
        contentSkeletonEl: HTMLElement;
        colContainerEls: HTMLElement[];
        fgContainerEls: HTMLElement[];
        bgContainerEls: HTMLElement[];
        mirrorContainerEls: HTMLElement[];
        highlightContainerEls: HTMLElement[];
        businessContainerEls: HTMLElement[];
        constructor(context: ComponentContext, el: HTMLElement, renderProps: RenderProps);
        processOptions(): void;
        computeLabelInterval(slotDuration: any): any;
        render(props: TimeGridProps): void;
        destroy(): void;
        updateSize(isResize: boolean): void;
        _renderSlats(dateProfile: DateProfile): void;
        renderSlatRowHtml(dateProfile: DateProfile): string;
        _renderColumns(cells: TimeGridCell[], dateProfile: DateProfile): void;
        _unrenderColumns(): void;
        renderContentSkeleton(): void;
        unrenderContentSkeleton(): void;
        groupSegsByCol(segs: any): any[];
        attachSegsByCol(segsByCol: any, containerEls: HTMLElement[]): void;
        getNowIndicatorUnit(): string;
        renderNowIndicator(segs: TimeGridSeg[], date: any): void;
        unrenderNowIndicator(): void;
        getTotalSlatHeight(): number;
        computeDateTop(when: DateMarker, startOfDayDate?: DateMarker): any;
        computeTimeTop(duration: Duration): any;
        computeSegVerticals(segs: any): void;
        assignSegVerticals(segs: any): void;
        generateSegVerticalCss(seg: any): {
            top: any;
            bottom: number;
    ***REMOVED***;
        buildPositionCaches(): void;
        buildColPositions(): void;
        buildSlatPositions(): void;
        positionToHit(positionLeft: any, positionTop: any): {
            col: any;
            dateSpan: {
                range: {
                    start: Date;
                    end: Date;
            ***REMOVED***;
                allDay: boolean;
        ***REMOVED***;
            dayEl: HTMLElement;
            relativeRect: {
                left: any;
                right: any;
                top: any;
                bottom: any;
        ***REMOVED***;
    ***REMOVED***;
        _renderEventDrag(state: EventSegUiInteractionState): void;
        _unrenderEventDrag(state: EventSegUiInteractionState): void;
        _renderEventResize(state: EventSegUiInteractionState): void;
        _unrenderEventResize(state: EventSegUiInteractionState): void;
        _renderDateSelection(segs: Seg[]): void;
        _unrenderDateSelection(segs: Seg[]): void;
***REMOVED***
***REMOVED***

declare module '@fullcalendar/timegrid/SimpleTimeGrid' {
    import { DateComponent, DateProfile, EventStore, EventUiHash, EventInteractionState, DateSpan, DateRange, DayTable, DateEnv, DateMarker, Slicer, Hit, ComponentContext ***REMOVED*** from '@fullcalendar/core';
    import TimeGrid, { TimeGridSeg ***REMOVED*** from '@fullcalendar/timegrid/TimeGrid';
    export interface SimpleTimeGridProps {
        dateProfile: DateProfile | null;
        dayTable: DayTable;
        businessHours: EventStore;
        eventStore: EventStore;
        eventUiBases: EventUiHash;
        dateSelection: DateSpan | null;
        eventSelection: string;
        eventDrag: EventInteractionState | null;
        eventResize: EventInteractionState | null;
***REMOVED***
    export { SimpleTimeGrid as default, SimpleTimeGrid ***REMOVED***;
    class SimpleTimeGrid extends DateComponent<SimpleTimeGridProps> {
        timeGrid: TimeGrid;
        constructor(context: ComponentContext, timeGrid: TimeGrid);
        destroy(): void;
        render(props: SimpleTimeGridProps): void;
        renderNowIndicator(date: DateMarker): void;
        buildPositionCaches(): void;
        queryHit(positionLeft: number, positionTop: number): Hit;
***REMOVED***
    export function buildDayRanges(dayTable: DayTable, dateProfile: DateProfile, dateEnv: DateEnv): DateRange[];
    export class TimeGridSlicer extends Slicer<TimeGridSeg, [DateRange[]]> {
        sliceRange(range: DateRange, dayRanges: DateRange[]): TimeGridSeg[];
***REMOVED***
***REMOVED***

declare module '@fullcalendar/timegrid/AllDaySplitter' {
    import { Splitter, EventDef, DateSpan ***REMOVED*** from '@fullcalendar/core';
    export { AllDaySplitter as default, AllDaySplitter ***REMOVED***;
    class AllDaySplitter extends Splitter {
        getKeyInfo(): {
            allDay: {***REMOVED***;
            timed: {***REMOVED***;
    ***REMOVED***;
        getKeysForDateSpan(dateSpan: DateSpan): string[];
        getKeysForEventDef(eventDef: EventDef): string[];
***REMOVED***
***REMOVED***

